name: Provision

on:
  workflow_dispatch:

jobs:

  setup:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.102
      - name: Install workload
        run: dotnet workload install aspire
      - name: Restore dependencies
        run: dotnet restore
      - name: Install azd
        uses: Azure/setup-azd@v0.1.0

  build:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: dotnet build --no-restore

  provision:
    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: Azure Provision
        run: azd provision --no-prompt --environment ${{ vars.AZURE_ENV_NAME }}

