name: Provision

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install azd
        uses: Azure/setup-azd@v0.1.0

      - name: Azure Dev Provision
        run: azd provision --no-prompt --environment ${{ vars.AZURE_ENV_NAME }}

